DROP TABLE HVIKT_FIBRE;
CREATE TABLE HVIKT_FIBRE ( 
 ID INTEGER PRIMARY KEY AUTOINCREMENT,
 LOCATION TEXT NOT NULL,
 TYPE TEXT NOT NULL,
 CONNECTOR_FROM TEXT NOT NULL,
 CONNECTOR_TO TEXT NOT NULL,
 LENGTH REAL NOT NULL,
 AMOUNT INT NOT NULL,
 UPDATED DATETIME,
 UPDATED_BY TEXT 
);