DROP TABLE HVIKT_FIBRE;
CREATE TABLE HVIKT_FIBRE ( 
 LOCATION TEXT NOT NULL,
 TYPE TEXT NOT NULL,
 CONNECTOR_FROM TEXT NOT NULL,
 CONNECTOR_TO TEXT NOT NULL,
 LENGTH REAL NOT NULL,
 AMOUNT INT NOT NULL,
 UPDATED DATETIME,
 UPDATED_BY TEXT,
 PRIMARY KEY(LOCATION, TYPE, CONNECTOR_FROM, CONNECTOR_TO, LENGTH)
);